In [28]:
#Neuron Neuron Architecture Functional API
from keras.models import Model 
from keras.layers import * 
import keras
import tensorflow as tf
tf.random.set_seed(34)
#from keras.layers import Input
#from keras.layers import concatenate
#from keras.layers import Dense

inputs=Input(shape=(2,))
h1_1=Dense(units=2,activation='relu')(inputs)
h1_2=Dense(units=2,activation='relu')(inputs)
c=concatenate([h1_1,h1_2])
h2=Dense(units=2,activation='relu')(c)
o=Dense(units=1,activation='sigmoid')(h2)
functional_model=Model(inputs,o)
functional_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 2)]          0           []                               
                                                                                                  
 dense_4 (Dense)                (None, 2)            6           ['input_2[0][0]']                
                                                                                                  
 dense_5 (Dense)                (None, 2)            6           ['input_2[0][0]']                
                                                                                                  
 concatenate_1 (Concatenate)    (None, 4)            0           ['dense_4[0][0]',                
                                                                  'dense_5[0][0]']          

In [29]:
#Weights and Bias when only inputs are given without training the model
functional_model.layers[0].get_weights()

[]

In [30]:
#Weights and Bias of first hidden layer without training the model
functional_model.layers[1].get_weights()

[array([[-0.6217317 ,  1.1573931 ],
        [ 0.23766792,  0.6021912 ]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [31]:
#Weights and Bias of Output layer without training the model
functional_model.layers[-1].get_weights()

[array([[-0.72977906],
        [-0.73399884]], dtype=float32), array([0.], dtype=float32)]

In [32]:
#To set weights to whole model
#model.set_weights(given_weights)

In [33]:
#OR Gate
import numpy as np
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[1],[1],[1]])

In [34]:
functional_model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [35]:
functional_model.fit(x,y,epochs=10,verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 946ms/step - loss: 1.0075 - accuracy: 0.2500
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 0.9973 - accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 0.9882 - accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 0.9794 - accuracy: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 0.9709 - accuracy: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 0.9626 - accuracy: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 0.9546 - accuracy: 0.0000e+00
Epoch 8/10
1/1 [==============================] - 0s 12ms/step - loss: 0.9469 - accuracy: 0.0000e+00
Epoch 9/10
1/1 [==============================] - 0s 13ms/step - loss: 0.9393 - accuracy: 0.0000e+00
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 0.9320 - accuracy: 0.0

In [36]:
loss,accuracy=functional_model.evaluate(x,y)

1/1 [==============================] - 0s 152ms/step - loss: 0.9249 - accuracy: 0.0000e+00


In [37]:
pred=functional_model.predict(x)
pred

1/1 [==============================] - 0s 62ms/step


array([[0.50902915],
       [0.4099942 ],
       [0.3846992 ],
       [0.319349  ]], dtype=float32)

In [38]:
functional_model.layers

In [39]:
hidden1=functional_model.layers[1]
weights,biases=hidden1.get_weights()

In [40]:
weights

array([[-0.6217317 ,  1.1480316 ],
       [ 0.22847134,  0.59302354]], dtype=float32)

In [41]:
biases

array([-0.00919659, -0.01360327], dtype=float32)

In [42]:
hiddenO=functional_model.layers[-1]
weights,biases=hiddenO.get_weights()

In [43]:
weights

array([[-0.6849982 ],
       [-0.73399884]], dtype=float32)

In [44]:
biases

array([0.03612061], dtype=float32)

In [45]:
#To get the weights and bias of all the layers
functional_model.get_weights()

[array([[-0.6217317 ,  1.1480316 ],
        [ 0.22847134,  0.59302354]], dtype=float32),
 array([-0.00919659, -0.01360327], dtype=float32),
 array([[ 0.44614547, -0.05070319],
        [-0.00640893,  0.8945204 ]], dtype=float32),
 array([-0.02075015, -0.00593562], dtype=float32),
 array([[ 0.8523089 , -0.1985023 ],
        [ 0.37121844, -0.568125  ],
        [ 0.82694674, -0.76446366],
        [ 0.2438368 , -0.27429986]], dtype=float32),
 array([-0.0345474,  0.       ], dtype=float32),
 array([[-0.6849982 ],
        [-0.73399884]], dtype=float32),
 array([0.03612061], dtype=float32)]

In [46]:
#Storing all the weights and bias in list
l=functional_model.get_weights()

In [47]:
#Increasing the value of weights and bias by 0.5 in the list l
for i in range(len(l)):
  for j in range(len(l[i])):
    l[i][j]=l[i][j]+0.5
l

[array([[-0.1217317 ,  1.6480316 ],
        [ 0.72847134,  1.0930235 ]], dtype=float32),
 array([0.49080342, 0.48639673], dtype=float32),
 array([[0.9461455 , 0.4492968 ],
        [0.49359107, 1.3945204 ]], dtype=float32),
 array([0.47924984, 0.4940644 ], dtype=float32),
 array([[ 1.352309  ,  0.3014977 ],
        [ 0.87121844, -0.06812501],
        [ 1.3269467 , -0.26446366],
        [ 0.7438368 ,  0.22570014]], dtype=float32),
 array([0.4654526, 0.5      ], dtype=float32),
 array([[-0.18499821],
        [-0.23399884]], dtype=float32),
 array([0.5361206], dtype=float32)]

In [48]:
#Current Assigned Weights and bias to the functional model
functional_model.get_weights()

[array([[-0.6217317 ,  1.1480316 ],
        [ 0.22847134,  0.59302354]], dtype=float32),
 array([-0.00919659, -0.01360327], dtype=float32),
 array([[ 0.44614547, -0.05070319],
        [-0.00640893,  0.8945204 ]], dtype=float32),
 array([-0.02075015, -0.00593562], dtype=float32),
 array([[ 0.8523089 , -0.1985023 ],
        [ 0.37121844, -0.568125  ],
        [ 0.82694674, -0.76446366],
        [ 0.2438368 , -0.27429986]], dtype=float32),
 array([-0.0345474,  0.       ], dtype=float32),
 array([[-0.6849982 ],
        [-0.73399884]], dtype=float32),
 array([0.03612061], dtype=float32)]

In [49]:
#Setting new weights and bias to the functional model
functional_model.set_weights(l)

In [50]:
#New Weights and bias of the functional model
functional_model.get_weights()

[array([[-0.1217317 ,  1.6480316 ],
        [ 0.72847134,  1.0930235 ]], dtype=float32),
 array([0.49080342, 0.48639673], dtype=float32),
 array([[0.9461455 , 0.4492968 ],
        [0.49359107, 1.3945204 ]], dtype=float32),
 array([0.47924984, 0.4940644 ], dtype=float32),
 array([[ 1.352309  ,  0.3014977 ],
        [ 0.87121844, -0.06812501],
        [ 1.3269467 , -0.26446366],
        [ 0.7438368 ,  0.22570014]], dtype=float32),
 array([0.4654526, 0.5      ], dtype=float32),
 array([[-0.18499821],
        [-0.23399884]], dtype=float32),
 array([0.5361206], dtype=float32)]

In [51]:
#Trainig the functional model using new weights and bias
functional_model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [53]:
mycallback=keras.callbacks.EarlyStopping(monitor = 'loss', mode = 'min', patience = 5, min_delta = 0.001)

In [55]:
functional_model.fit(x,y,epochs=10000,callbacks=mycallback,verbose=0)

In [56]:
loss,accuracy=functional_model.evaluate(x,y)

1/1 [==============================] - 0s 142ms/step - loss: 0.1023 - accuracy: 1.0000


In [57]:
pred=functional_model.predict(x)
pred

1/1 [==============================] - 0s 57ms/step


array([[0.27841294],
       [0.95565516],
       [0.96415246],
       [0.999126  ]], dtype=float32)