In [15]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(2,input_dim=2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_22 (Dense)            (None, 2)                 6         
                                                                 
 dense_23 (Dense)            (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [16]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(4,input_dim=4,activation='relu'))
model.add(Dense(2,activation='softmax'))
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 4)                 20        
                                                                 
 dense_25 (Dense)            (None, 2)                 10        
                                                                 
Total params: 30
Trainable params: 30
Non-trainable params: 0
_________________________________________________________________


In [17]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(2,input_dim=2,activation='relu'))
model.add(Dense(2,activation="sigmoid"))
model.add(Dense(2,activation='softmax'))
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_26 (Dense)            (None, 2)                 6         
                                                                 
 dense_27 (Dense)            (None, 2)                 6         
                                                                 
 dense_28 (Dense)            (None, 2)                 6         
                                                                 
Total params: 18
Trainable params: 18
Non-trainable params: 0
_________________________________________________________________


In [18]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(5,input_dim=2,activation='softmax'))
model.add(Dense(2,activation="relu"))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_29 (Dense)            (None, 5)                 15        
                                                                 
 dense_30 (Dense)            (None, 2)                 12        
                                                                 
 dense_31 (Dense)            (None, 1)                 3         
                                                                 
Total params: 30
Trainable params: 30
Non-trainable params: 0
_________________________________________________________________


In [19]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(3,input_dim=2,activation='relu'))
model.add(Dense(2,activation="sigmoid"))
model.add(Dense(2,activation='softmax'))
model.add(Dense(2,activation='relu'))
model.add(Dense(2,activation='softmax'))
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_32 (Dense)            (None, 3)                 9         
                                                                 
 dense_33 (Dense)            (None, 2)                 8         
                                                                 
 dense_34 (Dense)            (None, 2)                 6         
                                                                 
 dense_35 (Dense)            (None, 2)                 6         
                                                                 
 dense_36 (Dense)            (None, 2)                 6         
                                                                 
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [20]:
#Model for OR Gate
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(2,input_dim=2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_37 (Dense)            (None, 2)                 6         
                                                                 
 dense_38 (Dense)            (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [22]:
import numpy as np
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[1],[1],[1]])

In [23]:
history=model.fit(x,y,epochs=2000,verbose=0)

In [24]:
#Model for AND Gate
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(2,input_dim=2,activation='relu'))
model.add(Dense(2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
#model.summary()

In [25]:
model.layers[0].get_weights()

[array([[ 0.02254581,  0.3129741 ],
        [ 0.38185585, -0.55366313]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [26]:
model.get_weights()

[array([[ 0.02254581,  0.3129741 ],
        [ 0.38185585, -0.55366313]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.9274534 ,  1.2236236 ],
        [-0.33369166,  0.7207037 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.9442917],
        [-0.4983285]], dtype=float32),
 array([0.], dtype=float32)]

In [27]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [28]:
import numpy as np
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[0],[0],[1]])

In [29]:
history=model.fit(x,y,epochs=2000,verbose=0)

In [30]:
loss,accuracy=model.evaluate(x,y)

1/1 [==============================] - 0s 180ms/step - loss: 0.1249 - accuracy: 1.0000


In [31]:
print(loss)
print(accuracy)

0.12490513920783997
1.0


In [32]:
pred=model.predict(x)
pred=(model.predict(x)>0.5).astype(int)
pred

1/1 [==============================] - 0s 28ms/step


array([[0],
       [0],
       [0],
       [1]])

In [33]:
#Model for XOR Gate
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(2,input_dim=2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_42 (Dense)            (None, 2)                 6         
                                                                 
 dense_43 (Dense)            (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [35]:
import numpy as np
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[1],[1],[0]])

In [36]:
history=model.fit(x,y,epochs=1000,verbose=0)

In [37]:
loss,accuracy=model.evaluate(x,y)

1/1 [==============================] - 0s 137ms/step - loss: 0.6934 - accuracy: 0.2500


In [38]:
print(loss)
print(accuracy)

0.6933695077896118
0.25


In [39]:
pred=model.predict(x)
pred

1/1 [==============================] - 0s 58ms/step


array([[0.48290044],
       [0.49724978],
       [0.49738145],
       [0.51173526]], dtype=float32)